### ISSUE TITLE
Error when reconstructing Seamless data

### ISSUE THREAD

**Issue by starshine360** [kpu/preprocess#40]
When I use the `wet_lines` script (branch `wet`)to download and gather aligned text information from the metadata of Seamless (see: [Seamless Aligned data](https://github.com/facebookresearch/seamless_communication/blob/main/docs/m4t/seamless_align_README.md)), there is something wrong. The error message is showed as below. So what should I do to solve it? Look forward to your suggestion.

> preprocess/preprocess/warcstream.hh:37 in bool preprocess::WARCStream::GiveBytes(const char*, std::size_t, Callback&) [with Callback = DocumentCallback; std::size_t = long unsigned int] threw util::Exception because `ret != 0 && ret != 1'. zlib inflate returned unexpected code -3

**Comment by kpu** [comment]
The Internet is not as reliable is one might hope.  `wet_lines` is designed to carry on without retrying, but log what it was successful and unsuccessful at.  Retry the unsuccessful stuff again.  A few iterations of that and everything should download eventually.

**Comment by R4ZZ3** [comment]
@starshine360 How you were able to get that wet_lines line working?

When I try the build in the wet branch I get this error (I am not that familiar with compiling projects like this)

![image](https://github.com/kpu/preprocess/assets/25264037/c03ad0b8-1b98-4046-9235-c9526ba8775d)

**Comment by kpu** [comment]
`git submodule init && git submodule update`

**Comment by R4ZZ3** [comment]
Thanks @kpu!

After your advice and trying again I got this error
![image](https://github.com/kpu/preprocess/assets/25264037/225d8e7e-5d51-4dba-a27f-a8d49f53d768)

Then ran: sudo apt-get install libcurl-dev

And after that built went smoothly

**Comment by lzl-mt** [comment]
@kpu @R4ZZ3 Thanks for the suggestion! Have you successfully downloaded the data? I have tried for several times, cost almost one week but only got this ERROR: 
`what():  /home/ubuntu/preprocess/preprocess/wet_lines_main.cc:71 in void Retrieve::Add(util::StringPiece, const Extract&) threw util::Exception because `!extracts.empty() && extracts.back().paragraph_num     ber > extract.paragraph_number'. Metadata should be sorted by paragraph number in each document`
And i can not find any wav or text saved in my workspace, how can i fix it? Thx a lot.

**Comment by kpu** [comment]
Did you try sorting the metadata by paragraph number within each document?

**Comment by kpu** [comment]
Also, this is really meant to be sharded.  Use the `shard` program to split by commoncrawl file.
